version: "3"

services:
  node:
    build: .
    image: demo-line-teacher
    container_name: demo-line-teacher
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - collected_static:/app/public/
    command: npm start


volumes:
  collected_static:
