version: "3"

services:
  node:
    build: .
    image: demo-line-teacher
    container_name: demo-line-teacher
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - collected_static:/app/public/
    command: npm start
    networks:
      - shared_network


volumes:
  collected_static:

networks:
  shared_network:
    external: true
