
 

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
   
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_PROD_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_PROD_PEM }}
        port: 22
        script: |
          whoami
          cd /home/ubuntu/metablox_blockchain_service
          sudo git checkout main
          sudo git pull
          sudo chmod +x deploy.sh
          sudo sh deploy.sh
          sudo git checkout -- .
